Spinner Component UPDATE
Spinner Component removed from app.component.html to avoid execution errors.

Error: expressionchangedafterithasbeencheckederror: expression has changed after it was checked. previous value: 'false'. current value: 'true'.